before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: sGJ/MaT77Jd8zJPJc36ZBz2NZh0rP94Wy5oVmV5M/4/GnPVmcviOV0OlLQiy7iTiYciIeZcwxqhYKoET5UEDcaaY/8P+GaVx/vxlI/eRzmbtS3d02uVuefoB8QV7wpL+6vGb0EjfiF307a3FnvEMvUpEYLQ8OUgbKIMWZc7BMjg1L67PH3zUJI9ywlGW1xbNSiEP53W2RmnkNaXdgAdJhGpJCAoXXT0m8acBJq502E6CtV/zRCcTW/RtiS4pF70K/bxYDdBAMnsTZCgk4S9NkRKu1DMYHvu2tq/4E7XGbrP1yT+NcjcToHDWfIH7Yiwao7m+uCRao7y2zSCIOGsdwDLl97Fbja5f3FQ17NlCCcGrX4pus3HGCrjgfh8DV9haDVybAPQL455D4Vs2Zq56X72DXTHQ8iZxSseC5do3Jd/KHdst8oer++GdiAXkZBp0uflbtT01cWEfB6YuxZ79SMgNGmCPtm/DMkHAtZL//FlHp0u15KKOTxcRSPvWGfTGU7FilSUas8LpODheOqDHKCjrWHwG8c06nf6Bk4KNHQMeldljEoOKKKMv5U6EU3ffy7qpx/+a/5vT7bpxIn5Fa2LqNAca7C1ux74K6MFhe85kknHPDLyMjXk4snsyFlfbeVB1nym9331lR6KxER6dOu8Mx3xYA9PMPdvt52XBipA= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
